---
# Pre flight checks

# Assert target machine belong to redhat os family and version 9 or 10
- name: Validate tarrget operating system
  ansible.builtin.assert:
    that:
      - ansible_facts['os_family'] == 'RedHat'
      - ansible_facts['distribution_major_version'] in ['9', '10']
    fail_msg: "This role only supports RedHat / RHEL 9 and 10. Detected: {{ ansible_facts['distribution'] }} {{ ansible_facts['distribution_version'] }}"
    success_msg: "Target OS validated for Cockpit: {{ ansible_facts['distribution'] }} {{ ansible_facts['distribution_version'] }}"
